# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: heroku-invoices

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  region: eu-west-1
  runtime: nodejs8.10

# The `functions` block defines what code to deploy
functions:
  invoices:
    handler: handler.invoices
    # The `events` block defines how to trigger the handler.helloWorld code
    events:
      - http:
          path: invoices
          method: get
          cors: true
